### ISSUE TITLE
Allow disabling of viewport emulation

### ISSUE THREAD

**Issue by bobajeff** [mattsse/chromiumoxide#20]
Currently, the viewport will emulate a specified size or the default (800x600).
I'd like to be able to disable this when using the `Browser::connect()` as it looks weird otherwise.

![Screenshot_2021-01-04_20-45-15](https://user-images.githubusercontent.com/8573364/103601084-8403c080-4ece-11eb-939b-b0bfa8efb50f.png)

- Maybe we can pass a `BrowserConfig`  as a second parameter to `Browser::connect()`
   - And add `disable_viewport_emulation` field to the Viewport struct (set to `true` to disable viewport emulation.)

Similar to what Puppeteer does when you set `defaultViewport` to `null`.

**Comment by mattsse** [comment]
Hi,
thanks, good catch.
Right now the `EmulationManager` always [uses the `SetDeviceMetricsOverrideParams`](https://github.com/mattsse/chromiumoxide/blob/main/src/handler/emulation.rs#L25).
This should definitely be customizable and optional for `Browser::connect`. 

> Maybe we can pass a BrowserConfig as a second parameter to Browser::connect()
> And add disable_viewport_emulation field to the Viewport struct (set to true to disable viewport emulation.)

Yes, the `connect` should accept an additional config, since [`HandlerConfig` is used inside the `connect`](https://github.com/mattsse/chromiumoxide/blob/main/src/browser.rs#L52), I think we should either introduce a new config struct (`ConnectionConfig`?) or make `connect` accept `BrowserConfig` although we just use a subset of the `BrowserConfig`. 
Setting the viewpoint for `ConnectionConfig` then should be optional and result in optionally invoking the `SetDeviceMetricsOverrideParams` this requires refactoring of how the init commands are set, right now the [`EmulationManager` requires a `Viewport`](https://github.com/mattsse/chromiumoxide/blob/main/src/handler/target.rs#L329). 

To fix this issue we further need to make the [`viewport` of the `TargetConfig`](https://github.com/mattsse/chromiumoxide/blob/main/src/handler/target.rs#L489) optional.

Would you be comfortable with taking this on?
