### ISSUE TITLE
Page::event_listener() doesn't receive any events

### ISSUE THREAD

**Issue by bobajeff** [mattsse/chromiumoxide#28]
`Page::event_listener()` doesn't receive events. The following is a small test listening for `Fetch.requestPaused`: (I've also tried listening for other events and receive nothing).

```rust
use futures::StreamExt;
use chromiumoxide::error::Result;
use chromiumoxide::browser::Browser;
use chromiumoxide_cdp::cdp::browser_protocol::fetch;
mod get_debug_ws_url;

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let debug_ws_url = get_debug_ws_url::get_ws_url().await?;
    let (browser, mut handler) = 
    Browser::connect(debug_ws_url).await?;

    let handle = async_std::task::spawn(async move {
        loop {
            let _ = handler.next().await.unwrap();
        }
    });
    //Open new page to get page context
    let page = browser.new_page("http://www.example.com").await?;
    //send `Fetch.enable` - tells browser to pause on request to pattern (http://test/)
    page.execute(fetch::EnableParams {
        patterns: vec![
            fetch::RequestPattern {
            url_pattern: "http://test/*".to_string().into(),
            resource_type: None,
            request_stage: fetch::RequestStage::Request.into(),
        }].into(),
        handle_auth_requests: None,
    }).await?;
    //listen for `Fetch.requestPaused`
    let mut events = page.event_listener::<fetch::EventRequestPaused>().await?;
    async_std::task::spawn(async move {
        while let Some(event) = events.next().await {
            println!("Fetch.requestPaused");// Fetch.requestPaused is never recieved
        }
    });
    //navigate to http://test/
    page.goto("http://test/").await?; //this correctly pauses
        handle.await;
    Ok(())
}
```
Edit: Also, here's `get_debug_ws_url.rs`.
```rust
use std::collections::HashMap;

pub async fn get_ws_url() -> Result<std::string::String, Box<dyn std::error::Error>> {
    let resp = reqwest::get("http://127.0.0.1:9222/json/version")
        .await?
        .json::<HashMap<String, String>>()
        .await?;
        let web_socket_debugger_url = resp["webSocketDebuggerUrl"].clone();
    Ok(web_socket_debugger_url)
}
```

**Comment by mattsse** [comment]
My bad. somehow I forgot to actually poll the event handlers.
I checked your example and with #29 this works as expected now.

**Comment by bobajeff** [comment]
Thanks. I've checked everything and it seems to be working fine now.

I have a question. Is there a reason that you provide this functionality with futures stream for this instead of some function that takes a callback function eg. something like: `on_event(Eventkind, impl FnMut(Event) + 'static)`?

**Comment by mattsse** [comment]
I personally dislike callbacks in rust, because it creates all sorts of complications.
With a callback the caller loses control over where the control flow goes.
Rust's ownership model basically discourages you from using callbacks, because if you have an immutable reference to something, you can't have another mutable reference to it. So if you want to change something within your callback, the caller must already have mutable access to it and pass it to every callback (which makes callbacks pointless).
There are better patterns for this, such as the [`observer` pattern](https://github.com/lpxxn/rust-design-pattern/blob/master/behavioral/observer.rs)

My thinking behind this was, the `EventStream` as a `Stream<Item=Event>` gives you all utils from `futures::StreamExt` and doesn't limit you in what you want to do with a new event, the `EventStream` only provides you with the events.

**Comment by bobajeff** [comment]
Thanks. I'll look into the observer pattern. Although, I think callbacks must have a use in Rust since it supports them. And, it doesn't seem to be just as a kludge to work with C's FFI either.
