### ISSUE TITLE
Chrome stays idle infinitely

### ISSUE THREAD

**Issue by huy-vuong** [mattsse/chromiumoxide#49]
I've on macOS and set up `chromiumoxide` for use with `async-std`. I tried to scrape text from a webpage, and it looks like it hangs when calling `browser.new_page()`. Chrome says "Establishing secure connection..." and stays like that infinitely. It only terminates if I kill the process or <kbd>Cmd+Q</kbd> Chrome itself.

(I've also tried other URLs such as https://www.google.com too to see what happens and it loads fully (no throbber or "Establishing secure connection..." message), but still stays stuck endlessly.)

Is there something I'm missing that's causing things to stay running infinitely like this?

This is the code I'm running — it's an adaptation of the [Usage example on the crates.io page](https://crates.io/crates/chromiumoxide):

```rust
use chromiumoxide::browser::{Browser, BrowserConfig};
use futures::StreamExt;

#[async_std::main]
pub async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let url =
        "https://www.allrecipes.com/recipe/283601/sesame-seared-tuna-and-sushi-bar-spinach-salad/"
            .to_owned();
    let (browser, mut handler) =
        Browser::launch(BrowserConfig::builder().with_head().build()?).await?;
    println!("Created browser");
    let handle = async_std::task::spawn(async move {
        loop {
            let _ = handler.next().await.unwrap();
        }
    });
    println!("Created handle"); // Last print statement that actually executes.
    let page = browser.new_page(&url).await?;
    println!("Opened page to URL: {}", &url);
    let title = page
        .find_element("h1.headline.heading-content")
        .await?
        .inner_text()
        .await?
        .map(|text| text.trim().to_owned());
    println!(
        "title = {}",
        match title {
            Some(text) => text,
            None => "".to_owned(),
        }
    );
    handle.await;
    Ok(())
}
```

**Comment by clarkmcc** [comment]
I'm running into the same issue using the exact code here [https://github.com/mattsse/chromiumoxide/blob/main/examples/wiki-tokio.rs](https://github.com/mattsse/chromiumoxide/blob/main/examples/wiki-tokio.rs). My `Cargo.toml` matches the README. Any updates on this?
```toml
chromiumoxide = { git = "https://github.com/mattsse/chromiumoxide", features = ["tokio-runtime"], default-features = false, branch = "main"}
```

**Comment by clarkmcc** [comment]
After some experimentation, based on [this problem and solution](https://askubuntu.com/a/35414), it looks like this library cannot handle Chrome using an existing browser session. In other words, if you have a Chrome window open already, the Chrome binary that is started by chromiumoxide will use the existing browser session, but it will not know how to bootstrap itself into that browser session because the command does not return the web socket URL.

The workaround (which seems perfectly reasonable to me) is to specify a user data directory which forces Chrome to use create a new browser session:
```rust
BrowserConfig::builder().user_data_dir("/tmp").build()
```

**Comment by mattsse** [comment]
thanks for digging into this!
I guess there is no easy way to detect this ourself, so we need to make note of this somewhere, maybe add a note in the known issues section?

**Comment by clarkmcc** [comment]
Yeah, that seems like a great first step. There are a couple options that I can see

1. We dig into chrome a bit more and see how to get the ws URL for an existing browser session. That would solve the problem, but it means that we run everything within the context of a user's browser; that means user's passwords, user's history, etc. It seems like you'd rarely want to do this, so I feel like this should be explicit behavior.
2. We do something like what chromedp does and create our own temporary user-data-dirs in the system tmp folder every time we run. This guarantees a fresh instance of the browser. https://github.com/chromedp/chromedp/blob/ded6f35d3264c00fcfb622d3e06514fafd82bf46/allocate.go#L142-L151

I personally like option two better, especially since it will be familiar to users of chromedp (and likely puppeteer). I'd be happy to create a PR if that would be helpful.

**Comment by mattsse** [comment]
seems like option 1 has some drawbacks

option 2 sounds great, even though it requires some temp data.
happy to approve a PR for that :)
I feel like attaching a `tempdir` handle to the browser config or something could do the trick

**Comment by clarkmcc** [comment]
@mattsse I think I took a slightly different approach than what you were going for so feel free to point me in the right direction. I'm fairly new to Rust.

https://github.com/clarkmcc/chromiumoxide/commit/7b616de798178ebfd7484c426ee9da3923cdb411#diff-7afa191969629433e0edbd93702599f93162367fa42e197970ba31f32fcc79a9R522-R529
