### ISSUE TITLE
Navigation result

### ISSUE THREAD

**Issue by shulcsm** [mattsse/chromiumoxide#9]
Hello,
Is there a way to tell if page has successfully navigated or not? Ideally i want a response code. Puppeteers `goto` and `wait_for_navigation` seem to resolve to `HTTPResponse` Is that accessible somewhere or not implemented yet?

**Comment by mattsse** [comment]
Hi,
thanks for raising this.
Right now the [`Page:: wait_for_navigation`](https://github.com/mattsse/chromiumoxide/blob/main/src/page.rs#L147) only waits until the the new Page|Frame is loaded and then resolves.
Ideally we also want to monitor the request that issued the navigation. The `NetworkManager` will take care of take that, but is not yet implemented. 
I will add support for that shortly, but I'm not yet sure about how to integrate this within `wait_for_navigation`, because I want this to return `&Self` again. I think the best solution would be to add another function that does the same as `wait_for_navigation` but returns the actual response information as received from the websocket something like `fn wait_for_navigation_response(&self) -> Result<HttpResponse>`

**Comment by mattsse** [comment]
This has landed with #15

**Comment by shulcsm** [comment]
Hey, sorry for coming back to this so late, but it doesn't seem to work like advertised.
It seems to be returning random (last?) response, not the response for initial request.
